import Head from "next/head";
import { AppProps } from "next/app";
import "../styles/globals.css";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link key={1} rel="icon" href="/favicon2.ico" />
      </Head>
      <Component {...pageProps} />;
    </div>
  );
}

export default MyApp;
